#!/usr/bin/env bash
# install nginx on your web-01 server
# Nginx should be listening on port 80

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

sudo killall -9 nginx
sudo nginx &

echo "Hello World!" | sudo tee /var/www/html/index.html

curl -sI 127.0.0.1 | grep "Hello World!"
