#!/usr/bin/env bash
#install Nginx on web-01 server 
#allow HTTP traffic to access Nginx web server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
new_string="\t\tadd_header X-Served-By $(hostname);"
sed -i "s/^\tlocation \/ {$/&\n$new_string/" /etc/nginx/sites-available/default
service nginx restart
