#!/usr/bin/env bash
#install Nginx on web-01 server 
#allow HTTP traffic to access Nginx web server

sudo apt update
sudo apt install nginx -y
sudo ufw allow "Nginx HTTP"
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sed -i 's|server_name _;|server_name _;\n\tadd_header X-Served-By $hostname;|g' /etc/nginx/sites-available/default
sudo service nginx restart

