#!/usr/bin/env bash
#script that allows incoming traffic through tcp only port 22, 443 & 80

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
echo "y" | sudo ufw enable
