#!/usr/bin/env bash
#writing a bash script that configures an UBUNTU server
#localhost resolved to 127.0.0.2
#facebook.com resolved to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.old
echo -e "127.0.0.2\tlocalhost" > /etc/hosts.old
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts.old
sudo cp -f /etc/hosts.old /etc/hosts

