#!/usr/bin/env bash
#configuring nginx from root(super user) to nginx user

pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -H -u nginx bash -c "service nginx start"

